version: '3.8'
services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    depends_on:
      - protonmail
      - traefik
    volumes:
      - bitwarden:/data
    environment:
      - SIGNUPS_ALLOWED=${BITWARDEN_SIGNUPS_ALLOWED}
      - INVITATIONS_ALLOWED=${BITWARDEN_INVITATIONS_ALLOWED}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.bitwarden.entrypoints=websecure
        - traefik.http.routers.bitwarden.rule=Host(`${BITWARDEN_HOSTNAME}`)
        - traefik.http.routers.bitwarden.tls.certresolver=selfhostedservices
        - traefik.http.services.bitwarden.loadbalancer.server.port=80

  conduit:
    image: matrixconduit/matrix-conduit:latest
    restart: unless-stopped
    user: root
    depends_on:
      - traefik
    volumes:
      - conduit:/var/lib/matrix-conduit
    environment:
      - CONDUIT_ADDRESS=0.0.0.0
      - CONDUIT_ALLOW_ENCRYPTION=${CONDUIT_ALLOW_ENCRYPTION}
      - CONDUIT_ALLOW_FEDERATION=${CONDUIT_ALLOW_FEDERATION}
      - CONDUIT_ALLOW_REGISTRATION=${CONDUIT_ALLOW_REGISTRATION}
      - CONDUIT_CONFIG=''
      - CONDUIT_DATABASE_BACKEND=rocksdb
      - CONDUIT_DATABASE_PATH=/var/lib/matrix-conduit
      - CONDUIT_MAX_REQUEST_SIZE=${CONDUIT_MAX_REQUEST_SIZE}
      - CONDUIT_PORT=6167
      - CONDUIT_SERVER_NAME=${CONDUIT_SERVER_NAME}
      - CONDUIT_TRUSTED_SERVERS=${CONDUIT_TRUSTED_SERVERS}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
        - traefik.http.routers.conduit.entrypoints=websecure
        - traefik.http.routers.conduit.rule=Host(`${CONDUIT_HOSTNAME}`)
        - traefik.http.routers.conduit.tls.certresolver=selfhostedservices
        - traefik.http.routers.conduit.middlewares=cors-headers
        - traefik.http.services.conduit.loadbalancer.server.port=6167

  conduit-well-known:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - ./conduit/well-known.template:/etc/nginx/conf.d/conduit-well-known.template
    environment:
      - CONDUIT_HOSTNAME=${CONDUIT_HOSTNAME}
    command:
      /bin/bash -c "envsubst < /etc/nginx/conf.d/conduit-well-known.template >
      /etc/nginx/conf.d/conduit-well-known.conf && nginx -g 'daemon off;'"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
        - traefik.http.routers.conduit-well-known.entrypoints=websecure
        - 'traefik.http.routers.conduit-well-known.rule=Host(`${CONDUIT_SERVER_NAME}`)
          && PathPrefix(`/.well-known/matrix`)'
        - traefik.http.routers.conduit-well-known.tls.certresolver=selfhostedservices
        - traefik.http.routers.conduit-well-known.middlewares=cors-headers
        - traefik.http.services.conduit-well-known.loadbalancer.server.port=80

  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    depends_on:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.excalidraw.entrypoints=websecure
        - traefik.http.routers.excalidraw.rule=Host(`${EXCALIDRAW_HOSTNAME}`)
        - traefik.http.routers.excalidraw.tls.certresolver=selfhostedservices
        - traefik.http.services.excalidraw.loadbalancer.server.port=80

  ghost:
    image: ghost:alpine
    restart: unless-stopped
    depends_on:
      - ghost-db
      - protonmail
      - traefik
    volumes:
      - ghost:/var/lib/ghost/content
    environment:
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=${GHOST_DB_USER}
      - database__connection__password=${GHOST_DB_PASSWORD}
      - database__connection__database=${GHOST_DB_DATABASE}
      - url=https://${GHOST_HOSTNAME}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ghost.entrypoints=websecure
        - traefik.http.routers.ghost.rule=Host(`${GHOST_HOSTNAME}`)
        - traefik.http.routers.ghost.tls.certresolver=selfhostedservices
        - traefik.http.services.ghost.loadbalancer.server.port=2368

  ghost-db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ghost-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${GHOST_DB_DATABASE}
      - MYSQL_PASSWORD=${GHOST_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${GHOST_DB_PASSWORD}
      - MYSQL_USER=${GHOST_DB_USER}

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - jellyfin:/cache
      - jellyfin:/config
      - jellyfin-media:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_HOSTNAME}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.jellyfin.entrypoints=websecure
        - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOSTNAME}`)
        - traefik.http.routers.jellyfin.tls.certresolver=selfhostedservices
        - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    depends_on:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.libretranslate.entrypoints=websecure
        - traefik.http.routers.libretranslate.rule=Host(`${LIBRETRANSLATE_HOSTNAME}`)
        - traefik.http.routers.libretranslate.tls.certresolver=selfhostedservices
        - traefik.http.services.libretranslate.loadbalancer.server.port=5000

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - protonmail
      - redis
      - traefik
    volumes:
      - nextcloud:/config
      - nextcloud:/data
    environment:
      - PUID=${NEXTCLOUD_PUID}
      - PGID=${NEXTCLOUD_PGID}
      - TZ=${NEXTCLOUD_TIMEZONE}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.nextcloud.headers.browserXSSFilter=true
        - traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true
        - traefik.http.middlewares.nextcloud.headers.customRequestHeaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.nextcloud.headers.stsPreload=true
        - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
        - traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent=true
        - traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
        - traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/
        - traefik.http.routers.nextcloud.entrypoints=websecure
        - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-redirect
        - traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)
        - traefik.http.routers.nextcloud.tls.certresolver=selfhostedservices
        - traefik.http.services.nextcloud.loadbalancer.server.port=443
        - traefik.http.services.nextcloud.loadbalancer.server.scheme=https

  nextcloud-db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_DATABASE}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${NEXTCLOUD_DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  notes:
    image: standardnotes/web:stable
    restart: unless-stopped
    depends_on:
      - notes-gateway
      - traefik
    environment:
      - DASHBOARD_URL=http://standardnotes.com/dashboard
      - DEFAULT_SYNC_SERVER=https://${NOTES_SYNC_HOSTNAME}
      - PLANS_URL=https://standardnotes.com/plans
      - PURCHASE_URL=https://standardnotes.com/purchase
      - SECRET_KEY_BASE=${NOTES_SECRET_KEY_BASE}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.notes.entrypoints=websecure
        - traefik.http.routers.notes.rule=Host(`${NOTES_HOSTNAME}`)
        - traefik.http.routers.notes.tls.certresolver=selfhostedservices
        - traefik.http.services.notes.loadbalancer.server.port=3000

  notes-auth:
    image: standardnotes/auth:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
    entrypoint: [./packages/auth/docker/entrypoint.sh, start-web]
    env_file:
      - notes/base.env
      - notes/auth.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - DISABLE_USER_REGISTRATION=${NOTES_DISABLE_USER_REGISTRATION}
      - ENCRYPTION_SERVER_KEY=${NOTES_ENCRYPTION_SERVER_KEY}
      - JWT_SECRET=${NOTES_JWT_SECRET}
      - LEGACY_JWT_SECRET=${NOTES_LEGACY_JWT_SECRET}
      - PSEUDO_KEY_PARAMS_KEY=${NOTES_PSEUDO_KEY_PARAMS_KEY}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}

  notes-auth-worker:
    image: standardnotes/auth:latest
    restart: unless-stopped
    depends_on:
      - notes-auth
      - notes-db
      - redis
    entrypoint: [./packages/auth/docker/entrypoint.sh, start-worker]
    env_file:
      - notes/base.env
      - notes/auth.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - DISABLE_USER_REGISTRATION=${NOTES_DISABLE_USER_REGISTRATION}
      - ENCRYPTION_SERVER_KEY=${NOTES_ENCRYPTION_SERVER_KEY}
      - JWT_SECRET=${NOTES_JWT_SECRET}
      - LEGACY_JWT_SECRET=${NOTES_LEGACY_JWT_SECRET}
      - PSEUDO_KEY_PARAMS_KEY=${NOTES_PSEUDO_KEY_PARAMS_KEY}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}

  notes-db:
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - notes-db:/var/lib/mysql
      - notes-db:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=${NOTES_DB_DATABASE}
      - MYSQL_PASSWORD=${NOTES_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NOTES_DB_PASSWORD}
      - MYSQL_USER=${NOTES_DB_USER}

  notes-files:
    image: standardnotes/files:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
      - traefik
    entrypoint: [./packages/files/docker/entrypoint.sh, start-web]
    env_file: notes/base.env
    environment:
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}
      - MAX_CHUNK_BYTES={NOTES_FILE_MAX_UPLOAD_BYTES}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
        - traefik.http.routers.notes-files.entrypoints=websecure
        - traefik.http.routers.notes-files.rule=Host(`${NOTES_FILES_HOSTNAME}`)
        - traefik.http.routers.notes-files.tls.certresolver=selfhostedservices
        - traefik.http.routers.notes-files.middlewares=cors-headers
        - traefik.http.services.notes-files.loadbalancer.server.port=3000

  notes-gateway:
    image: standardnotes/api-gateway:latest
    restart: unless-stopped
    depends_on:
      - notes-auth
      - notes-sync
      - redis
      - traefik
    entrypoint: [./packages/api-gateway/docker/entrypoint.sh, start-web]
    env_file: notes/base.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - AUTH_SERVER_URL=http://notes-auth:3000
      - FILES_SERVER_URL=https://${NOTES_FILES_HOSTNAME}
      - SYNCING_SERVER_JS_URL=http://notes-sync:3000
      - WORKSPACE_SERVER_URL=http://notes-workspace:3000
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
        - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
        - traefik.http.routers.notes-gateway.entrypoints=websecure
        - traefik.http.routers.notes-gateway.rule=Host(`${NOTES_SYNC_HOSTNAME}`)
        - traefik.http.routers.notes-gateway.tls.certresolver=selfhostedservices
        - traefik.http.routers.notes-gateway.middlewares=cors-headers
        - traefik.http.services.notes-gateway.loadbalancer.server.port=3000

  notes-sync:
    image: standardnotes/syncing-server-js:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
    entrypoint: [./packages/syncing-server/docker/entrypoint.sh, start-web]
    env_file:
      - notes/base.env
      - notes/db.env
      - notes/sync.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}
      - FILES_SERVER_URL=https://${NOTES_FILES_HOSTNAME}

  notes-sync-worker:
    image: standardnotes/syncing-server-js:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - notes-sync
      - redis
    entrypoint: [./packages/syncing-server/docker/entrypoint.sh, start-worker]
    env_file:
      - notes/base.env
      - notes/db.env
      - notes/sync.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}
      - FILES_SERVER_URL=https://${NOTES_FILES_HOSTNAME}

  notes-workspace:
    image: standardnotes/workspace:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
    entrypoint: [./packages/workspace/docker/entrypoint.sh, start-web]
    env_file:
      - notes/base.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}

  notes-workspace-worker:
    image: standardnotes/workspace:latest
    restart: unless-stopped
    depends_on:
      - notes-db
      - notes-workspace
      - redis
    entrypoint: [./packages/workspace/docker/entrypoint.sh, start-worker]
    env_file:
      - notes/base.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}

  protonmail:
    image: ghcr.io/christoffercarlsson/protonmail-bridge:2.3.0
    restart: unless-stopped
    volumes:
      - protonmail:/root

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 1s
      timeout: 3s
      retries: 30

  traefik:
    image: traefik:v2.8
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --serverstransport.insecureskipverify=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.selfhostedservices.acme.tlschallenge=true
      - --certificatesresolvers.selfhostedservices.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.selfhostedservices.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - uptime-kuma:/app/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.uptime-kuma.entrypoints=websecure
        - traefik.http.routers.uptime-kuma.rule=Host(`${UPTIME_KUMA_HOSTNAME}`)
        - traefik.http.routers.uptime-kuma.tls.certresolver=selfhostedservices
        - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: self-hosted-services

volumes:
  bitwarden:
  conduit:
  ghost:
  ghost-db:
  jellyfin:
  jellyfin-media:
    external: true
  letsencrypt:
  nextcloud:
  nextcloud-db:
  notes-db:
  protonmail:
  uptime-kuma:
