services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - traefik
    volumes:
      - ${BITWARDEN_PATH}:/data
    environment:
      - SIGNUPS_ALLOWED=${BITWARDEN_SIGNUPS_ALLOWED}
      - INVITATIONS_ALLOWED=${BITWARDEN_INVITATIONS_ALLOWED}
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden.entrypoints=websecure
      - traefik.http.routers.bitwarden.rule=Host(`${BITWARDEN_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.bitwarden.tls.certresolver=selfhostedservices

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: unless-stopped
    volumes:
      - ${DDNS_UPDATER_PATH}:/updater/data
    network_mode: bridge
    environment:
      CONFIG: >-
        {
          "settings": [
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${BITWARDEN_SUBDOMAIN}",
              "key": "${BITWARDEN_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${EXCALIDRAW_SUBDOMAIN}",
              "key": "${EXCALIDRAW_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${JELLYFIN_SUBDOMAIN}",
              "key": "${JELLYFIN_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${LIBRETRANSLATE_SUBDOMAIN}",
              "key": "${LIBRETRANSLATE_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${NEXTCLOUD_SUBDOMAIN}",
              "key": "${NEXTCLOUD_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${NOTES_SUBDOMAIN}",
              "key": "${NOTES_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${NOTES_FILES_SUBDOMAIN}",
              "key": "${NOTES_FILES_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${NOTES_SYNC_SUBDOMAIN}",
              "key": "${NOTES_SYNC_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            },
            {
              "provider": "njalla",
              "domain": "${ROOT_DOMAIN}",
              "host": "${UPTIME_KUMA_SUBDOMAIN}",
              "key": "${UPTIME_KUMA_DOMAIN_KEY}",
              "ip_version": "ipv4",
              "provider_ip": true
            }
          ]
        }

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.entrypoints=websecure
      - traefik.http.routers.excalidraw.rule=Host(`${EXCALIDRAW_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.excalidraw.tls.certresolver=selfhostedservices

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - traefik
    volumes:
      - ${JELLYFIN_CACHE_PATH}:/cache
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_MEDIA_PATH}:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_SUBDOMAIN}.${ROOT_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.jellyfin.tls.certresolver=selfhostedservices
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.libretranslate.entrypoints=websecure
      - traefik.http.routers.libretranslate.rule=Host(`${LIBRETRANSLATE_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.libretranslate.tls.certresolver=selfhostedservices
      - traefik.http.services.libretranslate.loadbalancer.server.port=5000

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - redis
      - traefik
    networks:
      - nextcloud
      - traefik
    volumes:
      - ${NEXTCLOUD_CONFIG_PATH}:/config
      - ${NEXTCLOUD_APP_PATH}:/data
    environment:
      - PUID=${NEXTCLOUD_PUID}
      - PGID=${NEXTCLOUD_PGID}
      - TZ=${NEXTCLOUD_TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.nextcloud.headers.browserXSSFilter=true
      - traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nextcloud.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-redirect
      - traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.nextcloud.tls.certresolver=selfhostedservices
      - traefik.http.services.nextcloud.loadbalancer.server.port=443
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https

  nextcloud-db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - ${NEXTCLOUD_DB_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_DATABASE}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${NEXTCLOUD_DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  notes:
    image: standardnotes/web:stable
    container_name: notes
    restart: unless-stopped
    depends_on:
      - notes-gateway
      - traefik
    networks:
      - traefik
    environment:
      - DASHBOARD_URL=http://standardnotes.com/dashboard
      - DEFAULT_SYNC_SERVER=https://${NOTES_SYNC_SUBDOMAIN}.${ROOT_DOMAIN}
      - PLANS_URL=https://standardnotes.com/plans
      - PURCHASE_URL=https://standardnotes.com/purchase
      - SECRET_KEY_BASE=${NOTES_SECRET_KEY_BASE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.notes.entrypoints=websecure
      - traefik.http.routers.notes.rule=Host(`${NOTES_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.notes.tls.certresolver=selfhostedservices
      - traefik.http.services.notes.loadbalancer.server.port=3000

  notes-auth:
    image: standardnotes/auth:latest
    container_name: notes-auth
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
    networks:
      - notes
    entrypoint: [./packages/auth/docker/entrypoint.sh, start-web]
    env_file:
      - notes/base.env
      - notes/auth.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - DISABLE_USER_REGISTRATION=${NOTES_DISABLE_USER_REGISTRATION}
      - ENCRYPTION_SERVER_KEY=${NOTES_ENCRYPTION_SERVER_KEY}
      - JWT_SECRET=${NOTES_JWT_SECRET}
      - LEGACY_JWT_SECRET=${NOTES_LEGACY_JWT_SECRET}
      - PSEUDO_KEY_PARAMS_KEY=${NOTES_PSEUDO_KEY_PARAMS_KEY}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}

  notes-auth-worker:
    image: standardnotes/auth:latest
    container_name: notes-auth-worker
    restart: unless-stopped
    depends_on:
      - notes-auth
      - notes-db
      - redis
    networks:
      - notes
    entrypoint: [./packages/auth/docker/entrypoint.sh, start-worker]
    env_file:
      - notes/base.env
      - notes/auth.env
      - notes/db.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - DISABLE_USER_REGISTRATION=${NOTES_DISABLE_USER_REGISTRATION}
      - ENCRYPTION_SERVER_KEY=${NOTES_ENCRYPTION_SERVER_KEY}
      - JWT_SECRET=${NOTES_JWT_SECRET}
      - LEGACY_JWT_SECRET=${NOTES_LEGACY_JWT_SECRET}
      - PSEUDO_KEY_PARAMS_KEY=${NOTES_PSEUDO_KEY_PARAMS_KEY}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}

  notes-db:
    image: mysql:5.6
    container_name: notes-db
    restart: unless-stopped
    networks:
      - notes
    volumes:
      - ${NOTES_DATA_PATH}:/var/lib/mysql
      - ${NOTES_DATA_IMPORT_PATH}:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=${NOTES_DB_DATABASE}
      - MYSQL_PASSWORD=${NOTES_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NOTES_DB_PASSWORD}
      - MYSQL_USER=${NOTES_DB_USER}

  notes-files:
    image: standardnotes/files:latest
    container_name: notes-files
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
      - traefik
    networks:
      - notes
      - traefik
    entrypoint: [./packages/files/docker/entrypoint.sh, start-web]
    env_file: notes/base.env
    environment:
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}
      - MAX_CHUNK_BYTES={NOTES_FILE_MAX_UPLOAD_BYTES}
      - VALET_TOKEN_SECRET=${NOTES_VALET_TOKEN_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
      - traefik.http.routers.notes-files.entrypoints=websecure
      - traefik.http.routers.notes-files.rule=Host(`${NOTES_FILES_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.notes-files.tls.certresolver=selfhostedservices
      - traefik.http.routers.notes-files.middlewares=cors-headers
      - traefik.http.services.notes-files.loadbalancer.server.port=3000

  notes-gateway:
    image: standardnotes/api-gateway:latest
    container_name: notes-gateway
    restart: unless-stopped
    depends_on:
      - notes-auth
      - notes-sync
      - redis
      - traefik
    networks:
      - notes
      - traefik
    entrypoint: [./packages/api-gateway/docker/entrypoint.sh, start-web]
    env_file: notes/base.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - AUTH_SERVER_URL=http://notes-auth:3000
      - FILES_SERVER_URL=https://${NOTES_FILES_SUBDOMAIN}.${ROOT_DOMAIN}
      - SYNCING_SERVER_JS_URL=http://notes-sync:3000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=*
      - traefik.http.routers.notes-gateway.entrypoints=websecure
      - traefik.http.routers.notes-gateway.rule=Host(`${NOTES_SYNC_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.notes-gateway.tls.certresolver=selfhostedservices
      - traefik.http.routers.notes-gateway.middlewares=cors-headers
      - traefik.http.services.notes-gateway.loadbalancer.server.port=3000

  notes-sync:
    image: standardnotes/syncing-server-js:latest
    container_name: notes-sync
    restart: unless-stopped
    depends_on:
      - notes-db
      - redis
    networks:
      - notes
    entrypoint: [./packages/syncing-server/docker/entrypoint.sh, start-web]
    env_file:
      - notes/base.env
      - notes/db.env
      - notes/sync.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}
      - FILES_SERVER_URL=https://${NOTES_FILES_SUBDOMAIN}.${ROOT_DOMAIN}

  notes-sync-worker:
    image: standardnotes/syncing-server-js:latest
    container_name: notes-sync-worker
    restart: unless-stopped
    depends_on:
      - notes-db
      - notes-sync
      - redis
    networks:
      - notes
    entrypoint: [./packages/syncing-server/docker/entrypoint.sh, start-worker]
    env_file:
      - notes/base.env
      - notes/db.env
      - notes/sync.env
    environment:
      - AUTH_JWT_SECRET=${NOTES_AUTH_JWT_SECRET}
      - DB_DATABASE=${NOTES_DB_DATABASE}
      - DB_PASSWORD=${NOTES_DB_PASSWORD}
      - DB_USERNAME=${NOTES_DB_USER}
      - FILES_SERVER_URL=https://${NOTES_FILES_SUBDOMAIN}.${ROOT_DOMAIN}
      - FILE_UPLOAD_PATH=${NOTES_FILE_UPLOAD_PATH}

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - nextcloud
      - notes
    volumes:
      - ${NEXTCLOUD_REDIS_PATH}:/var/lib/redis
      - ${NOTES_REDIS_PATH}:/data
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 1s
      timeout: 3s
      retries: 30

  traefik:
    image: traefik:v2.8
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - ddns-updater
    networks:
      - traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --serverstransport.insecureskipverify=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.selfhostedservices.acme.tlschallenge=true
      - --certificatesresolvers.selfhostedservices.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.selfhostedservices.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${LETSENCRYPT_PATH}:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - traefik
    volumes:
      - ${UPTIME_KUMA_PATH}:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.rule=Host(`${UPTIME_KUMA_SUBDOMAIN}.${ROOT_DOMAIN}`)
      - traefik.http.routers.uptime-kuma.tls.certresolver=selfhostedservices
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nextcloud:
    name: nextcloud
  notes:
    name: notes
  traefik:
    name: traefik
