version: '3.8'
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    network_mode: bridge
    volumes:
      - ./config.json:/updater/data/config.json
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
