services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./config.json:/updater/data/config.json

networks:
  default:
    external: true
    name: self-hosted-services
